title: agentenv
description: Rewindable virtual environments for AI Agents
url: https://css521.github.io
baseurl: /agentenv

markdown: kramdown
kramdown:
  input: GFM

exclude:
  - openapi.json
  - "*.cast"
  - README.md
  - Gemfile.lock
